### ISSUE TITLE
Setup inicial do projeto

### ISSUE THREAD

**Issue by felipemotarocha** [fullstackclub-labs/fit-flow#2]
## Descrição da Funcionalidade 📝

Esse issue propõe a realização do setup inicial do projeto.

## Solução Proposta 💡

Vamos fazer a configuração das seguintes ferramentas:

- TypeScript & Next.js
- ESLint & Prettier
- Git Hooks
- Tailwind
- CI/CD (GitHub Actions)

## Benefícios Potenciais 🤩

Vamos garantir a consistência e qualidade do código do projeto. Além disso, criar uma base sólida para os futuros desenvolvimentos.

## Critérios de Aceitação ✅

- [ ] TypeScript & Next.js
- [ ] ESLint & Prettier
- [ ] Git Hooks (rodar `eslint --fix` e `prettier write` antes dos commits; garantir que mensagem do commit siga o padrão [Conventional](https://conventionalcommits.org/en/v1.0.0/)
- [ ] Tailwind
- [ ] CI/CD (rodar ESLint e Prettier nas Pull Requests e só permitir o `merge` caso ambos passem

**Comment by paulosantana95** [comment]
Fazendo ponte com oque já foi mencionado na atividade #16 . Acredito que esse essa [issue](https://github.com/filipedeschamps/tabnews.com.br/pull/71) de outro projeto pode nos ajudar com a questão do docker com o nosso banco de dados.
